USE MASTER
GO
DROP DATABASE IF EXISTS [DBTP]
CREATE DATABASE [DBTP]
GO
USE [DBTP]
GO
DROP TABLE IF EXISTS [User] 
CREATE TABLE [User](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
	[Username] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	[Birthday] DATETIME NOT NULL,
	[IsAdmin] BIT NOT NULL,
)

DROP TABLE IF EXISTS [Contact]
CREATE TABLE [Contact](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
	[FirstName] NVARCHAR(100) NOT NULL,
	[LastName] NVARCHAR(100) NOT NULL,
	[Adress] NVARCHAR(100) NULL,
	[PhoneNumber] NVARCHAR(15) NULL,
	[PhoneNumber2] NVARCHAR(15) NULL,
	[IsFavorite] BIT NOT NULL,
	[Birthday] DATETIME NULL,
	[Email] NVARCHAR(100) NULL,
	[User_Id] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id) NOT NULL,
)

GO
